language: node_js
node_js:
- '0.10'
after_script:
- npm install -g codeclimate-test-reporter
- codeclimate < ./coverage/lcov.info
deploy:
  provider: npm
  email: bvdrucker@gmail.com
  api_key:
    secure: t79WPYN2vfZIzl2n3LTzILzpcYUxV15MSpgqABcDJg8elGurzGV1LYCjT8deg2S1U+iRQ7hwFry9bf8TYQVs/fYRuVqz7Fq/nF1GtGT4G6pGQ3YiITPhCs6+5DX3T065XaLQqSv8h6cZjm7XBZBgyH8yheLUZDQcTkwK1iGSHVA=
  on:
    all_branches: true
    tags: true
    repo: bendrucker/angular-credit-cards
env:
  global:
    secure: VprXxdbEaxQv6evyuTkb7z+uCjdyZR2lxk1Roo8W08ba0uirpegpCw9jYN4ptv6gNwE8n3koiHsvczDat9KWZoqQ4nnUgEDwI67i2FSHrvQqsVgrzqJpSoIcGe96OTZJCe/dEh1Xh4IELHEt20piR8GChoE8mxLBi26ITyz03fk=
